### ISSUE TITLE
这里的前缀 ++ 是不是打多了呀

### ISSUE THREAD

**Issue by sakurafisch** [lightyears1998/angelica-c#1]
https://github.com/lightyears1998/angelica-c/blob/dc4f3cac6f65868e2c4f144a7fb5aa81c9f89689/Parser/cparser.cpp#L303

**Comment by lightyears1998** [comment]
确实。

出现这种错误说明测试不够充分。

这个“编译器”其实挺拉跨的，你可以去看看学悦的。

发件人: ***@***.***>
发送时间: 2021年11月26日 17:48
收件人: ***@***.***>
抄送: ***@***.***>
主题: [lightyears1998/angelica-c] 这里的前缀 ++ 是不是打多了呀 (Issue #1)


https://github.com/lightyears1998/angelica-c/blob/dc4f3cac6f65868e2c4f144a7fb5aa81c9f89689/Parser/cparser.cpp#L303

―

**Comment by lightyears1998** [comment]
确实。

出现这种错误说明测试不够充分。

这个“编译器”其实挺拉跨的，可以去看看 Lxy [做的](https://github.com/Lxy417165709/translater)那个，用上了比较好的技术。
